import { AiFillStar } from "react-icons/ai";

const data = [
    {
      id: "507f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      title: "Nike Air Monarch IV",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "white",
      category: "sneakers",
    },
    {
      id: "517f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "red",
      category: "sneakers",
    },
  
    {
      id: "527f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      title: "Nike Waffle One Sneaker",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "sneakers",
    },
    {
      id: "537f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      title: "Nike Running Shoe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Adidas",
      color: "black",
      category: "sneakers",
    },
    {
      id: "547f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      title: "Flat Slip On Pumps",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Vans",
      color: "green",
      category: "flats",
    },
    {
      id: "557f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      title: "Knit Ballet Flat",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "flats",
    },
  
    {
      id: "567f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      title: "Loafer Flats",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Vans",
      color: "white",
      category: "flats",
    },
  
    {
      id: "577f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      title: "Nike Zoom Freak",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "sneakers",
    },
  
    {
      id: "587f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Nike Men's Sneaker",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Adidas",
      color: "blue",
      category: "sneakers",
    },
  
    {
      id: "597f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      title: "PUMA BLACK-OCE",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "green",
      category: "sneakers",
    },
    {
      id: "507f191e810c19729de861ea",
      img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      title: "Pacer Future Sneaker",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "red",
      category: "sneakers",
    },
    {
      id: "507f191e810c19729de862ea",
      img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      title: "Unisex-Adult Super",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "black",
      category: "sneakers",
    },
    {
      id: "507f191e810c19729de863ea",
      img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
      title: "Roma Basic Sneaker",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "white",
      category: "sneakers",
    },
    {
      img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
      title: "Pacer Future Doubleknit",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "black",
      category: "sneakers",
    },
  
    {
      id: "507f191e810c19729de822ea",
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      title: "Fusion Evo Golf Shoe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Puma",
      color: "green",
      category: "sneakers",
    },
    {
      id: "517f191e810c19729de833ea",
      img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
      title: "Rainbow Chex Skate",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "red",
      category: "flats",
    },
    {
      id: "507f191e810c19729de222ea",
      img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
      title: "Low-Top Trainers",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "white",
      category: "sandals",
    },
    {
      id: "507f191e810c19729de911ea",
      img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
      title: "Vans Unisex Low-Top",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "blue",
      category: "sandals",
    },
    {
      id: "511f191e810c19729de220ea",
      img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
      title: "Classic Bandana Sneakers",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Nike",
      color: "black",
      category: "sandals",
    },
    {
      id: "577f191e811c19729de877ea",
      img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      title: "Chunky High Heel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Vans",
      color: "black",
      category: "heels",
    },
    {
      id: "557f191e877c19729de888ea",
      img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
      title: "Slip On Stiletto High Heel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "puma",
      color: "black",
      category: "heels",
    },
    {
      id: "567f191e810c29729de99ea",
      img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      title: "DREAM PAIRS Court Shoes",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Nike",
      color: "red",
      category: "heels",
    },
    {
      id: "557f191e810c33729de161ea",
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "red",
      category: "sneakers",
    },
  
    {
      id: "117f191e810c19729de811ea",
      img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
      title: "Low Mid Block Heels",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "black",
      category: "heels",
    },
    {
      id: "447f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
      title: "Chunky High Heel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "heels",
    },
    {
      id: "667f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
      title: "Amore Fashion Stilettos",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Adidas",
      color: "white",
      category: "heels",
    },
    {
      id: "777f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
      title: "Bridal Sandals Glitter",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "heels",
    },
    {
      id: "997f191e810c19729de860ea",
      img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
      title: "Wedding Prom Bridal",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "flats",
    },
  ];
  
  export default data;